name: Ultimate Free Cloud Server 2027
on: workflow_dispatch

jobs:
  launch-infrastructure:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Pre-Configure Automated SSH Keys
      run: |
        echo "⚡ Engineering Key Generation... ⚡"
        mkdir -p ~/.ssh
        ssh-keygen -t ed25519 -N "" -f ~/.ssh/id_ed25519
        chmod 700 ~/.ssh
        chmod 600 ~/.ssh/id_ed25519

    - name: Launch Free Linux Server & Connect Tunnel
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: false
        
