name: Ultimate Free Cloud Server 2027
on: workflow_dispatch

jobs:
  launch-infrastructure:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Engineering Automated Connection
      run: |
        echo "⚡ Bootstrapping Telemetry Tunnel... ⚡"
        sudo apt-get update && sudo apt-get install -y tmate
        
        # إنشاء نفق الاتصال خلف الكواليس وحفظ الرابط فورًا في ملف
        tmate -S /tmp/tmate.sock new-session -d
        tmate -S /tmp/tmate.sock wait-for-vnc
        
        # استخراج سطر الاتصال وحفظه في ملف نصوص بالرئيسية
        tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}' > ~/connection_link.txt
        echo "=========================================="
        echo "YOUR PRIVATE SSH CONNECTION LINK IS:"
        cat ~/connection_link.txt
        echo "=========================================="

    - name: Upload Connection Link as Artifact
      uses: actions/allowed-artifacts-action@v1
      with:
        name: server-access-key
        path: ~/connection_link.txt

    - name: Keep Server Alive
      run: |
        # إبقاء الخادم يعمل بأعلى كفاءة لمدة 6 ساعات متواصلة
        sleep 21600
        
